version: '3'

services:
  # MySQL Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: userwp
      MYSQL_PASSWORD: w0rdpress
    networks:
      - wpsite

  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passw0rd
    networks:
      - wpsite

  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8001:80'
    restart: unless-stopped    
    volumes: [ './:/var/www/html' ]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: userwp
      WORDPRESS_DB_PASSWORD: w0rdpress
    networks:
      - wpsite

networks:
  wpsite:
  
volumes:
  db_data:
